/**
 * mandate-registry deployment record. A4 deliverable, consumed by chain-gateway
 * (A7, A9) and by Owner C's dashboard (C10).
 *
 * `registry.json` is the single published artefact. Addresses are null until
 * deployed; `requireRegistryAddress` REFUSES on null rather than defaulting —
 * same rule as `mainnet.settlementRecipient` in constants.ts.
 */

import type { Abi } from "viem";
import registryJson from "../registry.json" with { type: "json" };
import { AppError, ErrorCode } from "./errors";
import type { Address, ChainId } from "./types";

export type RegistryFile = {
  addresses: Record<string, string | null>;
  deployBlock: Record<string, number | null>;
  abi: Abi;
};

const registry = registryJson as unknown as RegistryFile;

/** Generated by `forge build`, published via scripts/sync-registry.ts.
 *  Never hand-edit: a drift from the deployed bytecode surfaces as an opaque
 *  decode error hours later. */
export const MANDATE_REGISTRY_ABI: Abi = registry.abi;

export function getRegistryAddress(chainId: ChainId): Address | null {
  return registry.addresses[String(chainId)] ?? null;
}

export function getRegistryDeployBlock(chainId: ChainId): number | null {
  return registry.deployBlock[String(chainId)] ?? null;
}

/**
 * Extends AppError so it lands in the standard error envelope. As a plain
 * Error it fell through the Fastify handler and became a 500 INTERNAL, which
 * forced every caller to hand-wrap it — the wrapping was the smell.
 */
export class RegistryNotDeployedError extends AppError {
  constructor(chainId: ChainId) {
    super(
      400,
      ErrorCode.CHAIN_NOT_CONFIGURED,
      `mandate-registry is not deployed on chain ${chainId} — ` +
        `packages/contracts/registry.json has a null address. ` +
        `Deploy it and run scripts/sync-registry.ts.`,
    );
    this.name = "RegistryNotDeployedError";
  }
}

/** A null address must REFUSE, never default — §0, same rule as
 *  `mainnet.settlementRecipient`. */
export function requireRegistryAddress(chainId: ChainId): Address {
  const address = getRegistryAddress(chainId);
  if (address === null) throw new RegistryNotDeployedError(chainId);
  return address;
}
